name: Activity

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
      - uses: jamesgeorge007/github-activity-readme@master
        name: Update README.md with recent activities
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: ':zap: updated README.md with recent activities'
          MAX_LINES: 10
